name: downloads

networks:
  proxy:
    external: true   # Connect to the same proxy network for NPM access
  vpn:
    driver: bridge

services:
  # --- Gluetun: VPN client for qBittorrent
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${VPN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${VPN_WIREGUARD_ADDRESS}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=on
      - FIREWALL_VPN_INPUT_PORTS=8080
      - TZ=${TZ}
    volumes:
      - ${APPDATA_ROOT}/downloads/gluetun:/gluetun
      - /tmp/gluetun:/tmp/gluetun    # Needed for forwarded_port
    networks:
      - proxy
      - vpn

  # --- qBittorrent: torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
      - ${APPDATA_ROOT}/downloads/qbittorrent/config:/config
      - ${MEDIA_ROOT}/downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  # --- gluetun qbittorrent port manager
  gluetun-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:1.0
    container_name: gluetun-port-manager
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - qbittorrent
    environment:
      - QB_USERNAME=${QBITTORRENT_USER}
      - QB_PASSWORD=${QBITTORRENT_PASS}
      - CHECK_INTERVAL=30
      - QB_HOST=localhost
      - QB_PORT=8080
    volumes:
      - /tmp/gluetun:/tmp/gluetun
      - ${APPDATA_ROOT}/downloads/qbittorrent/config:/config

  # --- Prowlarr: indexer aggregator for Radarr/Sonarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_ROOT}/downloads/prowlarr/config:/config
    expose:
      - "9696"   # Web UI
    networks: [proxy]

  # --- Sonarr: manage and download TV shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_ROOT}/downloads/sonarr/config:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/downloads:/downloads
    expose:
      - "8989"   # Web UI
    networks: [proxy]
    depends_on:
      - qbittorrent
      - prowlarr

  # --- Radarr: manage and download movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_ROOT}/downloads/radarr/config:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads
    expose:
      - "7878"   # Web UI
    networks: [proxy]
    depends_on:
      - qbittorrent
      - prowlarr

  # --- Bazarr: download and manage subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${APPDATA_ROOT}/downloads/bazarr/config:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/tv:/tv
    expose:
      - "6767"   # Web UI
    networks: [proxy]
    depends_on:
      - radarr
      - sonarr
